
services:
  db:
    image: postgres:17
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d graduation_project_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev  # ← 開発環境用のDockerfileを指定
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
      - bundle_data:/usr/local/bundle:cached
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgresql_data:
  bundle_data: