services:
  - type: web
    name: graduation-project-15-q76n
    preDeployCommand: bundle exec rails db:migrate
    env: ruby
    buildCommand: "bundle install && rails db:migrate && rails assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: graduation-project-15-q76n-db
          property: connectionString

# databases:
  # - name: graduation-project-15-q76n-db
   #  databaseName: graduation_project_production
   #  user: graduation_project_user


# databases セクションはコメントアウト
# databases:
#   - name: graduation-project-db
#     plan: free
#     databaseName: graduation_project_production
#     user: graduation_project_user

